const assert = require('node:assert/strict');
const { test } = require('node:test');
const { mkdtempSync, writeFileSync, readFileSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
const { spawnSync } = require('node:child_process');
const { plan, verify, remap, sha256 } = require('./rehearsal.cjs');

// Public dummy addresses, not key-derived accounts. No credentials or RPC.
const addr = (n) => `0x${n.toString(16).padStart(40, '0')}`;
const fee = (fixed = '0') => ({
  fee_fixed: fixed,
  fee_percBips: '0',
  fee_min: '0',
  fee_max: '0',
  ccy_perMillion: '0',
  ccy_mirrorFee: false,
});
function fixture() {
  const token = (id, qty) => ({
    exists: true,
    stId: String(id),
    tokTypeId: '1',
    tokTypeName: 'TEST',
    batchId: '1',
    mintedQty: qty,
    currentQty: qty,
    ft_price: '0',
    ft_ledgerOwner: addr(0),
    ft_lastMarkPrice: '0',
    ft_PL: '0',
  });
  return {
    info: {
      network: 'synthetic-fixture',
      contractAddress: addr(999),
      contractType: '0',
      owners: [addr(1)],
      deploymentOwner: addr(1),
    },
    ledgerHash: 'old-native-hash',
    data: {
      whitelistAddresses: [addr(1), addr(2), addr(3)],
      accountEntities: ['1', '7', '7'],
      entitiesWithFeeOwners: [
        { id: '1', addr: addr(1) },
        { id: '7', addr: addr(2) },
      ],
      ledgerOwners: [addr(1), addr(2), addr(3)],
      ledgerOwnersFees: [1, 2, 3].map((n) => ({ currencies: [fee(String(n))], tokens: [fee()] })),
      ledgers: [token(1, '11'), token(2, '7'), token(3, '13')].map((t) => ({
        exists: true,
        tokens: [t],
        spot_sumQty: t.currentQty,
        spot_sumQtyMinted: t.currentQty,
        spot_sumQtyBurned: '0',
        ccys: [{ ccyTypeId: '1', balance: '0', reserved: '0', name: 'USD', unit: 'cents' }],
      })),
      secTokenBaseId: '1',
      secTokenMintedCount: '3',
      secTokenMintedQty: '31',
      secTokenBurnedQty: '0',
      globalSecTokens: [],
      transferedFullSecTokensEvents: [],
      ccyTypes: [{ id: '1', name: 'USD', unit: 'cents', decimals: '2' }],
      ccyFees: [fee('5'), fee('9')],
      tokenTypes: [{ id: '1', settlementType: '1', cashflowBaseAddr: addr(0) }],
      tokenFees: [fee('2'), fee('4')],
      batches: [
        {
          id: '1',
          tokTypeId: '1',
          mintedQty: '31',
          burnedQty: '0',
          originator: addr(1),
          origTokFee: fee('3'),
          origCcyFee_percBips_ExFee: '5',
          metaKeys: ['serial'],
          metaValues: ['keep-this'],
        },
      ],
    },
  };
}
function evidence(backup, block = '100') {
  const digest = sha256(JSON.stringify(backup));
  return {
    schemaVersion: 1,
    environment: 'rehearsal',
    entityId: '7',
    chainId: '31337',
    network: 'synthetic-fixture',
    contractAddress: addr(999),
    block: { number: block, hash: `0x${block === '100' ? 'a' : 'b'}`.padEnd(66, '0') },
    backupSha256: digest,
    scopeAccounts: [addr(2), addr(3)],
  };
}
function planned(backup = fixture()) {
  const e = evidence(backup);
  return plan(backup, e, e.backupSha256);
}
// Explicit expected snapshots; not generated by the implementation's burn plan.
function burned(complete = true) {
  const after = fixture();
  after.data.globalSecTokens = [{ ...after.data.ledgers[1].tokens[0], currentQty: '0' }];
  after.data.ledgers[1].tokens = [];
  after.data.ledgers[1].spot_sumQty = '0';
  after.data.ledgers[1].spot_sumQtyBurned = '7';
  if (complete) {
    after.data.globalSecTokens.push({ ...after.data.ledgers[2].tokens[0], currentQty: '0' });
    after.data.ledgers[2].tokens = [];
    after.data.ledgers[2].spot_sumQty = '0';
    after.data.ledgers[2].spot_sumQtyBurned = '13';
  }
  after.data.secTokenBurnedQty = complete ? '20' : '7';
  after.data.batches[0].burnedQty = complete ? '20' : '7';
  after.ledgerHash = 'new-native-hash';
  return after;
}
function checked(after, before = fixture()) {
  const pre = evidence(before);
  const post = evidence(after, '101');
  return verify(before, pre, pre.backupSha256, after, post, post.backupSha256);
}
function mapping(backup = burned()) {
  return {
    schemaVersion: 1,
    backupSha256: evidence(backup).backupSha256,
    path: "m/44'/60'/0'/0",
    addressCount: 10,
    entries: Array.from({ length: 10 }, (_, index) => ({
      index,
      oldAddress: addr(index + 1),
      newAddress: addr(index + 101),
    })),
    preservedAddresses: [],
  };
}
function mapped(backup = burned(), m = mapping(backup)) {
  const e = evidence(backup);
  return remap(backup, e, e.backupSha256, m);
}

test('plans only exact scoped tokens with deterministic evidence-bound IDs', () => {
  const result = planned();
  assert.deepEqual(
    result.operations.map(({ account, stId, quantity }) => ({ account, stId, quantity })),
    [
      { account: addr(2), stId: '2', quantity: '7' },
      { account: addr(3), stId: '3', quantity: '13' },
    ],
  );
  assert.deepEqual(planned(), result);
  const b = fixture();
  const e = evidence(b, '101');
  assert.notEqual(plan(b, e, e.backupSha256).operations[0].id, result.operations[0].id);
});

test('rejects wrong byte hash, environment, contract, membership, and duplicate scope', () => {
  for (const mutate of [
    (e) => {
      e.backupSha256 = '0'.repeat(64);
    },
    (e) => {
      e.environment = 'live';
    },
    (e) => {
      e.entityId = '0';
    },
    (e) => {
      e.entityId = '1';
    },
    (e) => {
      delete e.entityId;
    },
    (e) => {
      e.contractAddress = addr(888);
    },
    (e) => {
      e.scopeAccounts = [addr(2)];
    },
    (e) => {
      e.scopeAccounts = [addr(2), addr(2), addr(3)];
    },
  ]) {
    const b = fixture();
    const e = evidence(b);
    const digest = e.backupSha256;
    mutate(e);
    assert.throws(() => plan(b, e, digest));
  }
});

test('rejects currency, reserve, missing currency, futures, incomplete tokens and unsafe numbers', () => {
  for (const mutate of [
    (b) => {
      b.data.ledgers[1].ccys[0].balance = '1';
    },
    (b) => {
      b.data.ledgers[1].ccys[0].reserved = '1';
    },
    (b) => {
      b.data.ledgers[1].ccys = [];
    },
    (b) => {
      b.data.tokenTypes[0].settlementType = '2';
    },
    (b) => {
      b.data.secTokenMintedCount = '4';
    },
    (b) => {
      b.data.secTokenMintedQty = Number.MAX_SAFE_INTEGER + 1;
    },
    (b) => {
      b.data.ledgers[1].tokens[0].currentQty = '-1';
    },
    (b) => {
      b.data.batches[0].burnedQty = '1';
    },
  ]) {
    const b = fixture();
    mutate(b);
    assert.throws(() => planned(b));
  }
});

test('accepts exact int64 quantities without Number rounding and rejects the upper boundary', () => {
  const b = fixture();
  b.data.ledgers[1].tokens[0].currentQty = '9223372036854775807';
  b.data.ledgers[1].tokens[0].mintedQty = '9223372036854775807';
  b.data.ledgers[1].spot_sumQty = '9223372036854775807';
  b.data.secTokenMintedQty = '9223372036854775831';
  b.data.batches[0].mintedQty = '9223372036854775831';
  assert.equal(planned(b).operations[0].quantity, '9223372036854775807');
  b.data.ledgers[1].tokens[0].currentQty = '9223372036854775808';
  b.data.ledgers[1].tokens[0].mintedQty = '9223372036854775808';
  assert.throws(() => planned(b), /invalid token quantity/);
});

test('reports exact completed/pending operations and accepts repeated evidence', () => {
  const partial = checked(burned(false));
  const ops = planned().operations;
  assert.equal(partial.complete, false);
  assert.deepEqual(partial.completed, [ops[0].id]);
  assert.deepEqual(partial.pending, [ops[1].id]);
  const full = checked(burned());
  assert.equal(full.complete, true);
  assert.deepEqual(
    full.completed,
    ops.map((op) => op.id),
  );
  assert.deepEqual(checked(burned()), full);
  const b = fixture();
  const e = evidence(b);
  assert.equal(verify(b, e, e.backupSha256, b, e, e.backupSha256).completed.length, 0);
});

test('rejects partial burns even when all quantity counters reconcile', () => {
  const b = fixture();
  b.data.ledgers[1].tokens[0].currentQty = '6';
  b.data.ledgers[1].spot_sumQty = '6';
  b.data.ledgers[1].spot_sumQtyBurned = '1';
  b.data.secTokenBurnedQty = '1';
  b.data.batches[0].burnedQty = '1';
  assert.throws(() => checked(b), /partial quantity change/);
});

test('rejects disappearance, retained-state changes, counter drift, changed source and same-block mutation', () => {
  for (const mutate of [
    (b) => {
      b.data.globalSecTokens = [];
    },
    (b) => {
      b.data.ledgers[0].ccys[0].balance = '5';
    },
    (b) => {
      b.data.accountEntities[0] = '2';
    },
    (b) => {
      b.data.batches[0].metaValues = ['changed'];
    },
    (b) => {
      b.data.secTokenBaseId = '2';
    },
  ]) {
    const b = burned();
    mutate(b);
    assert.throws(() => checked(b));
  }
  const before = fixture();
  const after = burned();
  const pre = evidence(before);
  const post = evidence(after);
  assert.throws(
    () => verify(before, pre, pre.backupSha256, after, post, post.backupSha256),
    /within the pinned block/,
  );
  post.block.number = '101';
  post.chainId = '137';
  assert.throws(
    () => verify(before, pre, pre.backupSha256, after, post, post.backupSha256),
    /chain changed/,
  );
});

test('remaps typed fields only, preserves history/counters/source identity and does not mutate input', () => {
  const b = burned();
  const saved = structuredClone(b);
  const result = mapped(b);
  assert.equal(result.candidate.info.owners[0], addr(101));
  assert.equal(result.candidate.data.ledgerOwners[2], addr(103));
  assert.equal(result.candidate.data.entitiesWithFeeOwners[1].addr, addr(102));
  assert.equal(result.candidate.data.batches[0].originator, addr(101));
  assert.equal(result.candidate.info.contractAddress, addr(999));
  assert.equal(result.candidate.data.secTokenMintedCount, '3');
  assert.equal(result.candidate.data.secTokenBurnedQty, '20');
  assert.deepEqual(result.candidate.data.batches[0].metaValues, ['keep-this']);
  assert.equal(result.candidate.ledgerHash, undefined);
  assert.deepEqual(b, saved);
  assert.deepEqual(mapped(b), result);
});

test('rejects unsafe mappings, active scoped balances and arbitrary text replacement', () => {
  assert.throws(() => mapped(fixture()), /tokens remain/);
  for (const mutate of [
    (m) => {
      m.entries[1].index = 0;
    },
    (m) => {
      m.entries[1].newAddress = m.entries[0].newAddress;
    },
    (m) => {
      m.entries[0].newAddress = addr(2);
    },
    (m) => {
      m.entries[0].newAddress = addr(0);
    },
    (m) => {
      m.entries[0].newAddress = addr(999);
    },
    (m) => {
      m.preservedAddresses = [addr(1)];
    },
    (m) => {
      m.entries[0].oldAddress = addr(200);
    },
    (m) => {
      m.backupSha256 = '0'.repeat(64);
    },
  ]) {
    const b = burned();
    const m = mapping(b);
    mutate(m);
    assert.throws(() => mapped(b, m));
  }
  const b = burned();
  b.data.batches[0].metaValues = [`contact ${addr(1)}`];
  assert.throws(() => mapped(b), /old address remains/);
  const keyed = burned();
  keyed.data.ledgerOwnersFees[0][addr(1)] = 'unknown fee schema';
  assert.throws(() => mapped(keyed), /old address remains/);
});

test('rejects missing or truncated fees in both otherwise consistent snapshots', () => {
  for (const mutate of [
    (b) => {
      delete b.data.ccyFees;
      delete b.data.tokenFees;
    },
    (b) => {
      b.data.ccyFees.pop();
    },
    (b) => {
      b.data.tokenFees.pop();
    },
    (b) => {
      b.data.ledgerOwnersFees[0].currencies = [];
    },
    (b) => {
      delete b.data.ledgerOwnersFees[1].tokens;
    },
    (b) => {
      delete b.data.tokenFees[0].fee_fixed;
    },
    (b) => {
      b.data.ccyFees[0].ccy_mirrorFee = 'false';
    },
    (b) => {
      delete b.data.batches[0].origTokFee;
    },
  ]) {
    const pre = fixture();
    const post = burned();
    mutate(pre);
    mutate(post);
    assert.throws(() => checked(post, pre));
    assert.throws(() => mapped(post));
  }
});

test('rejects destinations already in source metadata, but preserves 32-byte hashes', () => {
  const b = burned();
  b.data.batches[0].metaValues = [addr(101)];
  assert.throws(() => mapped(b));
  const safe = burned();
  safe.data.batches[0].metaValues = [`${addr(101)}${'a'.repeat(24)}`];
  assert.deepEqual(
    mapped(safe).candidate.data.batches[0].metaValues,
    safe.data.batches[0].metaValues,
  );
});

test('CLI writes once, cannot overwrite input/output, and rejects unknown commands', () => {
  const dir = mkdtempSync(join(tmpdir(), 'snapshot-offline-test-'));
  try {
    const b = fixture();
    const backup = join(dir, 'backup.json');
    const e = join(dir, 'evidence.json');
    const out = join(dir, 'plan.json');
    writeFileSync(backup, JSON.stringify(b));
    writeFileSync(e, JSON.stringify(evidence(b)));
    const cli = join(__dirname, 'rehearsal.cjs');
    const run = (...args) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
    assert.equal(run('plan', backup, e, out).status, 0);
    assert.equal(JSON.parse(readFileSync(out, 'utf8')).operations.length, 2);
    assert.notEqual(run('plan', backup, e, out).status, 0);
    assert.notEqual(run('plan', backup, e, backup).status, 0);
    assert.equal(readFileSync(backup, 'utf8'), JSON.stringify(b));
    assert.notEqual(run('execute', backup, e, out).status, 0);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
